SPK_NAME = loudgain
SPK_VERS = 0.6.8
SPK_REV = 1
#SPK_ICON = src/transmission.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = Timothy
DESCRIPTION = loudgain is a versatile ReplayGain 2.0 loudness normalizer, based on the EBU R128/ITU BS.1770 standard (-18 LUFS) and supports FLAC/Ogg/MP2/MP3/MP4/M4A/ALAC/Opus/ASF/WMA/WAV/WavPack/AIFF/APE audio files. It uses the well-known mp3gain commandline syntax but will never modify the actual audio data.
SPK_LINKS = /usr/local/bin/loudgain:bin/loudgain
RELOAD_UI = no
STARTABLE = no
DISPLAY_NAME = Loudgain
CHANGELOG = ""

HOMEPAGE = https://github.com/Moonbase59/loudgain
LICENSE  = BSD2

include ../../mk/spksrc.spk.mk
